### ISSUE TITLE
[question] Is this script functional on Linux?

### ISSUE THREAD

**Issue by abitdodgy** [HyGear/diff-dwg#1]
I know the readme says support will be added later, but readmes get out of date :D

**Comment by HyGear** [comment]
Sorry, I have been so busy with my job that I haven't had time to update the script. To answer your question, the script should work in Linux if you modify all the references to Windows specific paths. Also, you will need to comment out the .replace("/","\\") methods that are used to correct the path to a Windows path.

**Comment by abitdodgy** [comment]
Thanks! That sounds simple enough.

**Comment by ankush** [comment]
I recently started using your script at work it's been very helpful.

I can work on porting to linux and send a PR, if you're interested.
