### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by connor016** [HyGear/diff-dwg#2]
I am new to python so likely not opening this correctly but get the following error when running python diff-dwg.pyw:

diff-dwg-master_eng_drwngs>python diff-dwg.pyw
  File "diff-dwg.pyw", line 137
    print "Drawing sizes match"
                              ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(print "Drawing sizes match")?

**Comment by HyGear** [comment]
Looks like you are using Python 3. This was written in Python 2.7 so it would need to be re-written for Python 3 syntax to work correctly.

**Comment by HyGear** [comment]
FYI...I have a newer version of the script (diff-dwg3.py) that is now Python 3 compatible.
